basePath: /api/v1
definitions:
  createProduct.CreateProductRequestDto:
    properties:
      company:
        type: string
      model:
        type: string
      price:
        type: integer
    type: object
  domain.Product:
    properties:
      company:
        type: string
      id:
        type: integer
      model:
        type: string
      price:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Backend-Go API Title
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Создать продукт
      parameters:
      - description: CreateProductRequestDto
        in: body
        name: JSON
        required: true
        schema:
          $ref: '#/definitions/createProduct.CreateProductRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Создать продукт
      tags:
      - Продукты
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Получить продукт по id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Product'
      summary: Получить продукт по id
      tags:
      - Продукты
schemes:
- http
swagger: "2.0"
