basePath: /api/v1
definitions:
  api.CreateProductRequestDto:
    properties:
      company:
        type: string
      model:
        type: string
      price:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Backend-Go API Title
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Создать продукт
      parameters:
      - description: CreateProductRequestDto
        in: body
        name: JSON
        required: true
        schema:
          $ref: '#/definitions/api.CreateProductRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Создать продукт
      tags:
      - Продукты
schemes:
- http
swagger: "2.0"
